# Generated by Django 3.0.5 on 2020-07-24 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MapCB', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Dati_Prezzi',
            new_name='DatiPrezzi',
        ),
    ]
