# Generated by Django 2.2.14 on 2020-07-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapCB', '0002_auto_20200724_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datiprezzi',
            name='id',
        ),
        migrations.AlterField(
            model_name='datiprezzi',
            name='data_inserimento',
            field=models.DateField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='datiprezzi',
            name='web_scraper_order',
            field=models.CharField(default='', max_length=20, primary_key=True, serialize=False),
        ),
    ]
