# Generated by Django 2.2.14 on 2020-07-25 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapCB', '0003_auto_20200725_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='datiprezzi',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datiprezzi',
            name='web_scraper_order',
            field=models.CharField(default='', max_length=20),
        ),
    ]
