# Generated by Django 2.2.14 on 2020-07-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapCB', '0005_auto_20200725_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datiprezzi',
            name='auto_increment_id',
        ),
        migrations.AddField(
            model_name='datiprezzi',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
