# Generated by Django 2.2.14 on 2020-07-25 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapCB', '0007_auto_20200725_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datiprezzi',
            name='metri_quadri',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
