# Generated by Django 2.2.14 on 2020-07-25 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapCB', '0009_auto_20200725_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datiprezzi',
            name='prezzo',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=9),
        ),
    ]
