# Generated by Django 2.2.14 on 2020-07-25 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapCB', '0011_auto_20200725_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datiprezzi',
            name='metri_quadri',
            field=models.DecimalField(decimal_places=2, default=-1.0, max_digits=5),
        ),
    ]
