# Generated by Django 2.2.14 on 2020-07-25 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MapCB', '0012_auto_20200725_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datiprezzi',
            name='metri_quadri',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='datiprezzi',
            name='prezzo',
            field=models.IntegerField(default=-1),
        ),
    ]
