# Generated by Django 2.2.14 on 2020-07-30 08:31

from django.db import migrations
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('MapCB', '0014_datiprezzi_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datiprezzi',
            name='id',
        ),
        migrations.AddField(
            model_name='datiprezzi',
            name='_id',
            field=djongo.models.fields.ObjectIdField(auto_created=True, default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
